# https://medium.com/@Keithweaver_/setting-up-github-actions-for-a-react-app-on-github-pages-f66b28c312ac
name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
        steps:
        - uses: actions/checkout@v1
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}  
        - name: Install Packages
          run: npm install     
        - name: Deploy to GH Pages
          run: |
            export GIT_USER="minzen"
            git config --global user.name "$GIT_USER"
            git config --global user.email "feetu.nyrhinen@gmail.com"
            npm run deploy        
      - name: Updating Domain
          run: echo "Update domain"
